version: "3.2"
networks:
  net:
services:
  apache-stanbol:
      image: 10.1.70.193:5000/apache-stanbol
      environment:
        - JAVA_OPTS=-Xmx1g -XX:MaxPermSize=256m
      ports:
        - "8080:8080"
      deploy:
        replicas: 2
        restart_policy:
          condition: on-failure
      networks:
        - net
  postgres:
      image: 10.1.70.193:5000/postgres:9.5.10
      environment:
        - POSTGRES_PASSWORD=password
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
        placement:
          constraints:
            - node.role == manager
      ports:
        - '5432:5432'
      networks:
        - net
  amino3:
    image: 10.1.70.193:5000/amino3:latest
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    ports:
      - '3000:3000'
    networks:
      - net
  elasticsearch:
    image: 10.1.70.193:5000/elasticsearch:5.6.6
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    networks:
          - net
  elasticsearch-head:
    image: 10.1.70.193:5000/elasticsearch-head:5.x
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    ports:
      - "9100:9100"
    networks:
      - net
  nginx:
    image: 10.1.70.193:5000/nginx:1.13.8
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
    ports:
        - '9200:9200'
    networks:
      - net
